#!/usr/bin/env python
# Copyright (C) 2007-2010 Samuel Abels.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
import os, sys
from optparse           import OptionParser
from Config             import Config
from Exscript.util.file import get_hosts_from_csv

__version__ = '0'

parser = OptionParser(usage = '%prog [options] filename', version = __version__)
parser.add_option('--config',
                  dest    = 'config',
                  metavar = 'FILE',
                  help    = '''
The XML config file for seed.
'''.strip())

# Parse options.
options, args = parser.parse_args(sys.argv)
args.pop(0)

if not options.config:
    parser.error('Required option --config not set')

try:
    filename = args.pop()
except IndexError:
    parser.error('Missing filename')

config = Config(options.config)
hostdb = config.get_hostdb()

print 'Deleting old hosts...'
hostdb.delete_host()

print 'Importing new hosts...'
hostdb.save_host(get_hosts_from_csv(filename))
